### ISSUE TITLE
Unefficient implementation

### ISSUE THREAD

**Issue by Qumeric** [HenrYxZ/dijkstra-map#2]
I stumbled upon the original Dijkstra map article and found the concept very useful but the implementation idea is weird.

The whole algorithm can be implemented as a simple BFS. To make it work, BFS shall start not from a single cell (as usual) but from all goal cells.

Such implementation is not only more efficient but also shorter and easier to understand.

Please see my own custom implementation in case my explanation was not sufficiently clear:
```
def create_dijkstra_map(self):
    game_map = self.entity.game_map
    dijkstra_map = np.full((game_map.width, game_map.height), np.inf)

    queue: deque[tuple[int, int, int]] = deque()

    for x in range(game_map.width):
        for y in range(game_map.height):
            if self.entity.explored[x, y] == False and game_map.tiles["walkable"][x, y]:
                dijkstra_map[x, y] = 0
                queue.append((x, y, 0))

    while queue:
        x, y, distance = queue.popleft()
        neighbors = game_map.get_neighbors(x, y)
        for nx, ny in neighbors:
            if dijkstra_map[nx, ny] == np.inf and game_map.tiles["walkable"][nx, ny] and game_map.get_blocking_entity_at_location(nx, ny) is None:
                dijkstra_map[nx, ny] = distance + 1
                queue.append((nx, ny, distance + 1))

return dijkstra_map
```

Please tell me if I am missing something and original implementation is better/different in some way.

**Comment by HenrYxZ** [comment]
Hi thanks for commenting! 🙂
I think that implementation shouldn't be much more efficient if so, it's the same idea. The current algorithm is also pretty much BFS, and if you look at the code, the first pass is adding the goal cells in the queue, and then iterates looking at the neighbors until all are in the closed list
